---
- name: FFmpeg
  hosts: all
  become: true
  tasks:
    - name: (Debian) Ensure FFmpeg is installed
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name: ffmpeg
        state: present
        update_cache: true
    - name: (CentOS) Ensure FFmpeg is installed
      when: ansible_os_family == 'RedHat'
      block:
      - name: (CentOS) Ensure RPM fusion is installed
        ansible.builtin.dnf:
          disable_gpg_check: true
          name: https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
          state: present
      - name: (CentOS) Ensure FFmpeg is installed
        ansible.builtin.dnf:
          name: ffmpeg
          state: present

- name: PyCA
  hosts: all
  become: true
  tasks:
  - name: (Debian) Ensure PyCA is installed
    when: ansible_os_family == 'Debian'
    block:
      - name: (Debian) Ensure the necessary packages are installed
        ansible.builtin.apt:
          name: ['apt-transport-https', 'ca-certificates', 'gnupg']
          state: present
          update_cache: true
      - name: (Debian) Ensure the key is on the keyring
        ansible.builtin.apt_key:
          url: https://pyca.deb.opencast.org/gpg.key
          state: present
      - name: (Debian) Ensure opencast-pyca.list in sources.list.d is present and has the right contents
        ansible.builtin.copy:
          content: deb [arch=all] https://pyca.deb.opencast.org/opencast-pyca buster main
          dest: /etc/apt/sources.list.d/opencast-pyca.list
          mode: '644'
      - name: (Debian) Ensure PyCA is installed
        ansible.builtin.apt:
          name: opencast-pyca
          state: present
          update_cache: true
  - name: (CentOS) Ensure PyCA is installed
    when: ansible_os_family == 'RedHat'
    block:
      - name: (CentOS) Ensure lkiesow/pyca is enabled
        community.general.copr:
          name: lkiesow/pyca
          state: enabled
      - name: (CentOS) Ensure EPEL is installed
        ansible.builtin.dnf:
          name: epel-release
          state: present
      - name: (CentOS) Ensure PyCA is installed
        ansible.builtin.dnf:
          name: pyca
          state: present
  - name: Ensure the PyCA services are started and enabled (1/6)
    ansible.builtin.systemd:
      name: pyca-agentstate.service
      enabled: true
      state: started
  - name: Ensure the PyCA services are started and enabled (2/6)
    ansible.builtin.systemd:
      name: pyca-capture.service
      enabled: true
      state: started
  - name: Ensure the PyCA services are started and enabled (3/6)
    ansible.builtin.systemd:
      name: pyca-ingest.service
      enabled: true
      state: started
  - name: Ensure the PyCA services are started and enabled (4/6)
    ansible.builtin.systemd:
      name: pyca-schedule.service
      enabled: true
      state: started
  - name: Ensure the PyCA services are started and enabled (5/6)
    ansible.builtin.systemd:
      name: pyca-ui.service
      enabled: true
      state: started
  - name: Ensure the PyCA services are started and enabled (6/6)
    ansible.builtin.systemd:
      name: pyca.service
      enabled: true
      state: started
...
