---

- name: FFmpeg and pyCA on the respective platforms
  ansible.builtin.include_tasks: "{{ {'debian': 'debian', 'redhat': 'centos'}\
    [ansible_os_family | lower] }}-{{ item }}.yml"
  loop:
    - ffmpeg
    - pyca

- name: Services
  ansible.builtin.include_tasks: services.yml

...
