---

- name: Ensure the pyCA services are started and enabled
  become: true
  ansible.builtin.systemd:
    name: '{{ item }}.service'
    enabled: true
    state: started
  loop:
    - pyca-agentstate
    - pyca-capture
    - pyca-ingest
    - pyca-schedule
    - pyca-ui
    - pyca

...
