---

name: static-analysis

on:
  push:
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
      - run: pip install yamllint flake8 bandit
      - run: yamllint roles/ .github/workflows/
      - run: flake8 roles/
      - run: bandit -r roles/

...
