---

name: static-analysis

'on':
  push:
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
      - run: pip install yamllint flake8 bandit
      - run: yamllint -s roles/ .github/workflows/
        id: yamllint
        continue-on-error: true
      - run: flake8 roles/
        id: flake8
        continue-on-error: true
      - run: bandit -r roles/
        id: bandit
        continue-on-error: true
      - run: 'false'  # Fail the workflow if one of the analyzers complained
        if: ${{ steps.flake8.outcome != 'success' }}

...
